Document: kubeedge
Title: Debian kubeedge Manual
Author: <insert document author here>
Abstract: This manual describes what kubeedge is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kubeedge/kubeedge.sgml.gz

Format: postscript
Files: /usr/share/doc/kubeedge/kubeedge.ps.gz

Format: text
Files: /usr/share/doc/kubeedge/kubeedge.text.gz

Format: HTML
Index: /usr/share/doc/kubeedge/html/index.html
Files: /usr/share/doc/kubeedge/html/*.html
